apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manutest-rag-gitlab-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/manutest-rag-gitlab/overlays/development
    repoURL: https://github.com/fpetk/manutest-rag-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
