apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-manutest-rag-gitlab-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-manutest-rag-gitlab-gitops
    spec:  
      serviceAccountName: manutest-rag-gitlab-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=manutest-rag-gitlab-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/manutest-rag-gitlab-notebook -- git clone https://github.com/fpetk/manutest-rag
      restartPolicy: Never