apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: manutest-rag-gitlab
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: manutest-rag-gitlab 
  name: manutest-rag-gitlab
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: manutest-rag-gitlab 
