apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: manutest-rag-gitlab-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: manutest-rag-gitlab-database 
  name: manutest-rag-gitlab-database
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: manutest-rag-gitlab-database 
